name: Release

on:
  release:
    types:
      - published

permissions: {}

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4

      - name: Adjust version number
        shell: bash
        env:
          VERSION: ${{ github.event.release.tag_name }}
        run: |
          yq -i -o json ".version=\"${VERSION}\"" \
            "${{ github.workspace }}/custom_components/umami/manifest.json"

      - name: Create release ZIP
        shell: bash
        run: |
          cd "${{ github.workspace }}/custom_components/umami"
          zip umami.zip -r ./

      - name: Upload release asset
        uses: softprops/action-gh-release@v2
        with:
          files: "${{ github.workspace }}/custom_components/umami/umami.zip"
